/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CopyTradingRouteImport } from './routes/copy-trading'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksProcessJobsRouteImport } from './routes/api/public/hooks/process-jobs'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyTradingRoute = CopyTradingRouteImport.update({
  id: '/copy-trading',
  path: '/copy-trading',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessJobsRoute =
  ApiPublicHooksProcessJobsRouteImport.update({
    id: '/api/public/hooks/process-jobs',
    path: '/api/public/hooks/process-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/copy-trading': typeof CopyTradingRoute
  '/history': typeof HistoryRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/profile': typeof ProfileRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strategies': typeof StrategiesRoute
  '/terminal': typeof TerminalRoute
  '/wallet': typeof WalletRoute
  '/api/public/hooks/process-jobs': typeof ApiPublicHooksProcessJobsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/copy-trading': typeof CopyTradingRoute
  '/history': typeof HistoryRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/profile': typeof ProfileRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strategies': typeof StrategiesRoute
  '/terminal': typeof TerminalRoute
  '/wallet': typeof WalletRoute
  '/api/public/hooks/process-jobs': typeof ApiPublicHooksProcessJobsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/copy-trading': typeof CopyTradingRoute
  '/history': typeof HistoryRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/profile': typeof ProfileRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/strategies': typeof StrategiesRoute
  '/terminal': typeof TerminalRoute
  '/wallet': typeof WalletRoute
  '/api/public/hooks/process-jobs': typeof ApiPublicHooksProcessJobsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/copy-trading'
    | '/history'
    | '/investments'
    | '/login'
    | '/markets'
    | '/profile'
    | '/security'
    | '/signup'
    | '/sitemap.xml'
    | '/strategies'
    | '/terminal'
    | '/wallet'
    | '/api/public/hooks/process-jobs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/copy-trading'
    | '/history'
    | '/investments'
    | '/login'
    | '/markets'
    | '/profile'
    | '/security'
    | '/signup'
    | '/sitemap.xml'
    | '/strategies'
    | '/terminal'
    | '/wallet'
    | '/api/public/hooks/process-jobs'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/copy-trading'
    | '/history'
    | '/investments'
    | '/login'
    | '/markets'
    | '/profile'
    | '/security'
    | '/signup'
    | '/sitemap.xml'
    | '/strategies'
    | '/terminal'
    | '/wallet'
    | '/api/public/hooks/process-jobs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  CopyTradingRoute: typeof CopyTradingRoute
  HistoryRoute: typeof HistoryRoute
  InvestmentsRoute: typeof InvestmentsRoute
  LoginRoute: typeof LoginRoute
  MarketsRoute: typeof MarketsRoute
  ProfileRoute: typeof ProfileRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StrategiesRoute: typeof StrategiesRoute
  TerminalRoute: typeof TerminalRoute
  WalletRoute: typeof WalletRoute
  ApiPublicHooksProcessJobsRoute: typeof ApiPublicHooksProcessJobsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy-trading': {
      id: '/copy-trading'
      path: '/copy-trading'
      fullPath: '/copy-trading'
      preLoaderRoute: typeof CopyTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-jobs': {
      id: '/api/public/hooks/process-jobs'
      path: '/api/public/hooks/process-jobs'
      fullPath: '/api/public/hooks/process-jobs'
      preLoaderRoute: typeof ApiPublicHooksProcessJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  CopyTradingRoute: CopyTradingRoute,
  HistoryRoute: HistoryRoute,
  InvestmentsRoute: InvestmentsRoute,
  LoginRoute: LoginRoute,
  MarketsRoute: MarketsRoute,
  ProfileRoute: ProfileRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StrategiesRoute: StrategiesRoute,
  TerminalRoute: TerminalRoute,
  WalletRoute: WalletRoute,
  ApiPublicHooksProcessJobsRoute: ApiPublicHooksProcessJobsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
